#!/bin/bash

# Run the official Jekyl docker image.

docker start instantpot && exit 0

COMMAND=${1:-serve}

    # --rm \
docker run \
    --label=jekyll \
    --name=instantpot \
    --volume=$(pwd):/srv/jekyll \
    -it \
    -p 127.0.0.1:4000:4000 \
    jekyll/jekyll \
    jekyll $COMMAND
